/**:
  ros__parameters:
    number_of_joints: 7                                                         # We need this to split up the position arrays
    joint_config_names: ["home", "ready", "multi"]                              # We need to declare them here so we can search them by name
    home:
        positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        times: [5.0]
    ready:
        positions: [-1.5708, -0.785, -1.5708, -1.5708, -0.900, -1.5708, 0.000]
        times: [5.0]
    multi:
        positions: [-0.785, -1.5708, -1.5708, -2.300, 0.00, -0.785, 0.00,
                    -1.5708, -0.785, -1.5708, -1.5708, -0.900, 1.5708, 0.000,
                    0.000,  0.000,  0.000,  0.000, 0.000,  0.0000,  0.000]
        times: [4.0, 8.0, 12.0]
