/**:
  ros__parameters:
    tolerance:
        timeout: 0.1                               # s                      
        joint: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # rad
        pose:
            position: 0.2                          # m
            orientation: 1.0                       # rad
        twist:
            linear: 0.5                            # m/s
            angular: 1.0                           # rad/s
