/**:
  ros__parameters:
    pose_names: ["up", "down", "left", "right", "fore", "aft", "round"] # We need to declare them here so we can search them by name
    up:
        poses: [0.0, 0.0, 0.3, 0.0, 0.0, 0.0]
        times: [3.0]
        reference: "relative"
    down:
        poses: [0.0, 0.0, -0.3, 0.0, 0.0, 0.0]
        times: [3.0]
        reference: "relative"
    left:
        poses: [0.0, 0.3, 0.0, 0.0, 0.0, 0.0]
        times: [3.0]
        reference: "relative"
    right:
        poses: [0.0, -0.3, 0.0, 0.0, 0.0, 0.0]
        times: [3.0]
        reference: "relative"
    fore:
        poses: [0.3, 0.0, 0.0, 0.0, 0.0, 0.0]
        times: [3.0]
        reference: "relative"
    aft:
        poses: [-0.3, 0.0, 0.0, 0.0, 0.0, 0.0]
        times: [3.0]
        reference: "relative"
    round:
        poses: [0.70, -0.25, 0.7, 0.0, -3.1416, 0.0,
                0.70,  0.15, 0.7, 0.0, -3.1416, 0.0,
                0.70,  0.15, 0.5, 0.0, -3.1416, 0.0,
                0.70, -0.25, 0.5, 0.0, -3.1416, 0.0,
                0.70, -0.25, 0.7, 0.0, -3.1416, 0.0]
        times: [3.0, 6.0, 9.0, 12.0, 18.0]
        reference: "absolute"
